name: CI Pipeline Simple

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Recupérer le code
        uses: actions/checkout@v3

      - name: Installer Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint avec flake8
        run: |
          flake8 app --count --select=E9,F63,F7,F82,F841 --show-source --statistics
          flake8 app --count --max-complexity=10 --max-line-length=127 --statistics
          flake8 tests --count --max-line-length=127 --statistics

      - name: Lancer les tests avec pytest et coverage
        run: |
          # On installe le projet en mode éditable pour que 'app' soit reconnu
          pip install -e .
          pytest